# Generated by Django 4.2.20 on 2025-10-03 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_details', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('payment_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('emergency_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizedTrip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=200)),
                ('total_participants', models.IntegerField(default=0)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_cost_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_details', models.TextField()),
                ('accommodation_details', models.TextField()),
                ('meal_arrangements', models.TextField()),
                ('trip_status', models.CharField(choices=[('planning', 'Planning'), ('open', 'Open for Registration'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=200)),
                ('itinerary', models.TextField(blank=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.CharField(choices=[('leisure', 'Leisure/Vacation'), ('business', 'Business'), ('adventure', 'Adventure'), ('cultural', 'Cultural Experience'), ('religious', 'Religious/Pilgrimage'), ('family', 'Family Visit'), ('other', 'Other')], max_length=50)),
                ('budget_range', models.CharField(choices=[('budget', 'Budget (< 5,000 BDT)'), ('mid-range', 'Mid-Range (5,000 - 15,000 BDT)'), ('luxury', 'Luxury (> 15,000 BDT)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('max_participants', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_trip_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('driver_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operational_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='trips.organizedtrip')),
            ],
            options={
                'verbose_name_plural': 'Revenues',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('refund_status', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trips.organizedtrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='organizedtrip',
            name='travel_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_trip', to='trips.travelplan'),
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('face_verification_done', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='trips.organizedtrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['join_date'],
                'unique_together': {('trip', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TravelMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('compatibility_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_plan_1', to='trips.travelplan')),
                ('travel_plan_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_plan_2', to='trips.travelplan')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'unique_together': {('travel_plan_1', 'travel_plan_2')},
            },
        ),
    ]
