# Generated by Django 5.2.5 on 2025-10-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date_recorded'], 'verbose_name_plural': 'Revenues'},
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('status_before', models.CharField(max_length=20)),
                ('status_after', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='trips.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
