# Generated by Django 5.2.5 on 2025-10-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_revenue_options_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name_plural': 'Revenues'},
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
