# Generated by Django 5.2.5 on 2025-10-18 03:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_revenue_options_delete_paymenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizedtrip',
            name='driver_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment amount for the assigned driver', max_digits=10),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='accommodation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Accommodation fee per person', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='accommodation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='admin_warning',
            field=models.TextField(blank=True, help_text='Admin warning about this plan if inconsistencies detected', null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trips', to='trips.driver'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='combined_transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Combined transportation (transportation_cost + driver_payment) shown to users', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='driver_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Payment amount for the assigned driver for this specific trip', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='final_cost_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='food_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Food/meals cost per person', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='join_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='meal_arrangements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='other_costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Other miscellaneous costs per person', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='platform_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('finalized', 'Finalized'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Transportation cost per person (includes driver payment)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='transportation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number for this trip', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Dietary restrictions, medical needs, or special requests', null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='budget_range',
            field=models.CharField(choices=[('budget', 'Budget (< 10,000 BDT)'), ('mid-range', 'Mid-Range (10,000 - 30,000 BDT)'), ('luxury', 'Luxury (30,000 - 50,000 BDT)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='max_participants',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='purpose',
            field=models.CharField(choices=[('leisure', 'Leisure/Vacation'), ('adventure', 'Adventure'), ('cultural', 'Cultural Experience'), ('religious', 'Religious/Pilgrimage'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='TravelPlanInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('agreed', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='trips.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plan_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('plan', 'user')},
            },
        ),
    ]
